.Dd February 20 2020
.Dt N-OF 1
.nh
.Os
.Sh NAME
.Nm n-of
.Nd pick N lines from standard input
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar count
.Ek
.Sh DESCRIPTION
.Nm
picks 
.Ar count
lines (or fewer) from standard input and displays them.
.Sh EXIT STATUS
.Ex -std
.Nm
exits with a non-zero status if no lines are supplied.
.Sh EXAMPLES
These are more or less equivalent though
.Nm
will be more efficient though
.Nm
will not shuffle the order of the items selected, beyond what happens
randomly as lines are selected into the internal cache.
.Pp
.Dl $ Ic ... \&| n-of 7
.Dl $ Ic ... \&| shuffle \&| head -7
.Pp
.Nm
can filter down a large input list, and that can then be shuffled
if need be:
.Pp
.Dl $ Ic ... \&| n-of 7 \&| shuffle
.Sh SEE ALSO
.Xr coinflip 1 ,
.Xr oneof 1 ,
.Xr randline 1 ,
.Xr roll 1 ,
.Xr shuffle 1
.Sh AUTHOR
.An Jeremy Mates
.Sh CAVEATS
Only at most
.Dv INT32_MAX
lines can be selected for (or less, depending on the input and various
memory limits).
