CFLAGS=-std=c99 -O2 -Wall -pedantic -fno-diagnostics-color -fstack-protector-strong -fPIC -fPIE -pie -pipe

miditimer: miditimer.c
pedaltime: pedaltime.c
pianoteq: pianoteq.c

clean:
	git clean --force -x

.PHONY: clean
