.Dd June 17 2021
.Dt PLAYIT 1
.nh
.Os
.Sh NAME
.Nm playit
.Nd renders, previews, and plays lilypond data
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar lilypond-file
.Ek
.Sh DESCRIPTION
.Nm
runs
.Xr lilypond 1
on the provided
.Ar lilypond-file ,
opens the resulting PDF, and plays the resulting MIDI file (unless the
system is mute).
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Usually
.Nm
is run something along the lines of
.Pp
.Dl $ Ic aslines foo.ly \&| entr -c playit foo.ly
.Pp
which might be abstracted to something like
.Pp
.Dl #!/bin/sh
.Dl aslines \&"$@\&" \&| entr -c playit \&"$1\&"
.Pp
should multiple files be involved.
.Sh SEE ALSO
.Xr lilypond 1 ,
.Xr midiutil 1 ,
.Xr mopen 1 ,
.Xr tlymidity 1
.Sh AUTHOR
.An Jeremy Mates
