#!/usr/bin/env perl
#
# bigterm - launches a big (or sometimes small) terminal. must agree
# with ~/.Xdefaults (see dotfiles repo)

use feature qw(say);

@bigterms = qw(cous cous2 mf rogue wr);
@shell    = qw(/bin/ksh -l);

if (@ARGV) {
    $ARGV[0] =~ s/^rogue$/wr/;
    if ( grep { $ARGV[0] eq $_ } @bigterms ) {
        delete $ENV{TMUX};
        exec 'solitary', $ENV{HOME},
          qw(xterm -tn xterm-256color +bc +bdc +cm +dc +itc -class),
          "$ARGV[0]term", '-e', @shell;
        die "exec failed: $!\n";
    }
}

say join ' ', @bigterms;
