#!/bin/sh
QUIET=0
OPT=
while getopts q OPT; do
   case "$OPT" in
      q) QUIET=1 ;;
   esac
done
if [ x"`sndioctl output.mute`" == xoutput.mute=1 ]; then
   [ "$QUIET" -eq 0 ] && echo mute
   exit 0
fi
exit 1
